services:
  func-app-1:
    image: ${FUNCTION_APP_1_IMAGE}
    platform: linux/amd64
    ports:
      - "${FUNCTION_APP_1_HTTP_PORT}:80"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:80/api/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      - ASPNETCORE_ENVIRONMENT=${DOTNET_ENVIRONMENT:-production}
      - AzureWebJobsStorage=${AZURITE_CONNECTION_STRING}
      - OTEL_SERVICE_NAME=${FUNCTION_APP1_OLTP_NAME}
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT}
      - OTEL_EXPORTER_OTLP_HEADERS=${OTEL_EXPORTER_OTLP_HEADERS:-}
      - FUNCTIONS_EXTENSION_VERSION=~4
      - WEBSITES_ENABLE_APP_SERVICE_STORAGE=false
      - APPLICATIONINSIGHTS_CONNECTION_STRING=${APPLICATIONINSIGHTS_CONNECTION_STRING:-}
    depends_on:
      azurite:
        condition: service_healthy
    networks:
      - azure_container_apps_net
