services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    volumes:
      - ${VOLUMES_PATH}/azurite/data:/data
    command: "azurite --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0 --skipApiVersionCheck"
    healthcheck:
      test: nc 127.0.0.1 10000 -z
      interval: 1s
      retries: 30
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    networks:
      - azure_container_apps_net
networks:
  azure_container_apps_net:
    driver: bridge
